#!/usr/bin/env python3
"""The cases reduce.py must accept, and the ones it must refuse.

THE REFUSE CASES ARE THE HALF THAT MATTERS, and they outnumber the accept cases here on
purpose. Criterion 6 asks that a disagreement be detectable, and a reduction that accepts
everything would satisfy criterion 5 by being blind. So this suite is mostly an attempt to make
the reduction say yes to something it should not.

Run it with no arguments. Exit status is 0 when every case behaves, 1 otherwise, and a failing
case prints what it expected beside what it got.

This suite was shown to go red before it was committed. See the project README for which
mutations were applied to reduce.py and which cases caught each.
"""
from __future__ import annotations

import sys

from reduce import Refusal, reduce_capture

CLOCK = 280_000_000
PERIOD_S = 0.001
RESOLUTION_S = 0.00001  # ten microseconds, the witness's own limit


def capture(
    counts: list[int] | None = None,
    edges: list[float] | None = None,
    clock: int | None = CLOCK,
    guard: str | None = "ok",
    resolution: float | None = RESOLUTION_S,
    extra: str = "",
) -> str:
    """Build a capture file as text, so no fixture lives on disk and drifts from the parser."""
    lines = ["# generated by test_reduce.py"]
    if clock is not None:
        lines.append(f"clock_hz {clock}")
    if guard is not None:
        lines.append(f"wrap_guard {guard}")
    if resolution is not None:
        lines.append(f"resolution_s {resolution}")
    if counts is None:
        counts = [int(PERIOD_S * CLOCK)] * 40
    if edges is None:
        edges = [i * PERIOD_S for i in range(41)]
    lines.append("a_counts " + " ".join(str(c) for c in counts))
    lines.append("b_edges_s " + " ".join(f"{e:.9f}" for e in edges))
    if extra:
        lines.append(extra)
    return "\n".join(lines) + "\n"


# EVERY CASE CATCHES THE UNEXPECTED EXCEPTION TOO, and that is not boilerplate. A mutation
# removing the clock-rate refusal let a zero clock reach a division, so the suite ended in a
# traceback rather than in a reported failure. It was red, which is what the mutation run asked
# for, but it named nothing. A suite that reports WHICH case broke is worth more than one that
# merely returns a nonzero status, because the mutation matrix is read by a person.
def must_agree(name: str, text: str) -> bool:
    try:
        agree, _ = reduce_capture(text)
    except Refusal as exc:
        print(f"FAIL {name}: expected agreement, got a refusal, {exc}")
        return False
    except Exception as exc:  # noqa: BLE001
        print(f"FAIL {name}: expected agreement, the reduction raised {exc!r}")
        return False
    if not agree:
        print(f"FAIL {name}: expected agreement, the reduction reported a disagreement")
        return False
    return True


def must_disagree(name: str, text: str) -> bool:
    try:
        agree, _ = reduce_capture(text)
    except Refusal as exc:
        print(f"FAIL {name}: expected a reported disagreement, got a refusal, {exc}")
        return False
    except Exception as exc:  # noqa: BLE001
        print(f"FAIL {name}: expected a reported disagreement, the reduction raised {exc!r}")
        return False
    if agree:
        print(f"FAIL {name}: expected a reported disagreement, the reduction agreed")
        return False
    return True


def must_refuse(name: str, text: str) -> bool:
    try:
        reduce_capture(text)
    except Refusal:
        return True
    except Exception as exc:  # noqa: BLE001
        # A refusal is a reasoned message a reader can act on. Any other exception means the
        # reduction fell over instead of declining, which is a different defect and is reported
        # as one rather than being quietly accepted as "it did not produce a result".
        print(f"FAIL {name}: expected a refusal, the reduction raised {exc!r}")
        return False
    print(f"FAIL {name}: expected a refusal, the reduction produced a result")
    return False


def main() -> int:
    ok = True

    # The accept cases. Two, because an accept case only has to show the instrument works at
    # all, and there is no credit for a long list of them.
    ok &= must_agree("a clean capture agrees", capture())
    ok &= must_agree(
        "jitter inside the witness's resolution still agrees",
        capture(counts=[int(PERIOD_S * CLOCK) + (i % 7) * 200 for i in range(40)]),
    )

    # CRITERION 6 ITSELF. The period is deliberately changed on one instrument and the
    # reduction has to say so. Fifty microseconds is five times what the witness can resolve,
    # so a reduction that misses it is not merely imprecise.
    ok &= must_disagree(
        "criterion 6: a period changed by 50 us is reported",
        capture(edges=[i * (PERIOD_S + 0.00005) for i in range(41)]),
    )
    ok &= must_disagree(
        "a period changed in the other direction is reported",
        capture(edges=[i * (PERIOD_S - 0.00005) for i in range(41)]),
    )
    ok &= must_disagree(
        "a difference just over the tolerance is reported",
        capture(edges=[i * (PERIOD_S + RESOLUTION_S * 1.5) for i in range(41)]),
    )

    # WHY THE MEDIAN AND NOT THE MEAN, as a case rather than as a sentence in the design.
    # Thirty-nine periods at the nominal rate and one that took ten times as long. The median
    # does not move and the capture still agrees with the witness; a mean would be dragged
    # 225 us away, which is twenty-two times the tolerance. Without this case the choice of
    # statistic is untested, and a mutation replacing one with the other survived the first
    # version of this suite.
    ok &= must_agree(
        "one late sample does not move the median",
        capture(counts=[int(PERIOD_S * CLOCK)] * 39 + [int(PERIOD_S * CLOCK) * 10]),
    )

    # The refuse cases. Each is a way a capture can look reasonable and mean nothing.
    ok &= must_refuse("no clock rate", capture(clock=None))
    ok &= must_refuse("a clock rate of zero, which is how an unconfirmed tree reports", capture(clock=0))
    ok &= must_refuse("the wrap guard is unknown", capture(guard="unknown"))
    ok &= must_refuse("the wrap guard failed", capture(guard="wrapped"))
    ok &= must_refuse("no resolution, so agreement has no tolerance", capture(resolution=None))
    ok &= must_refuse("a resolution of zero", capture(resolution=0.0))
    # These two isolate ONE floor each, and the first version of this suite did not. It was
    # short on both instruments at once, so removing the cycle-counter floor left the witness
    # floor to refuse the capture anyway and the mutation survived. A redundant check hides a
    # missing test.
    ok &= must_refuse(
        "too few cycle counts, with plenty of witness edges",
        capture(counts=[280000] * 4),
    )
    ok &= must_refuse(
        "enough counts but too few witness edges",
        capture(edges=[i * PERIOD_S for i in range(5)]),
    )
    ok &= must_refuse(
        "a zero count, which no elapsed region produces",
        capture(counts=[280000] * 39 + [0]),
    )
    ok &= must_refuse(
        "witness edges out of order",
        capture(edges=[i * PERIOD_S for i in range(41)][:20][::-1] + [i * PERIOD_S for i in range(21, 42)]),
    )
    ok &= must_refuse("a key given twice, so which one is the run", capture(extra=f"clock_hz {CLOCK}"))
    ok &= must_refuse("an unknown key", capture(extra="sample_rate 1000"))
    ok &= must_refuse("a key with no value", capture(extra="clock_hz"))
    ok &= must_refuse("a count that does not parse", capture().replace("a_counts 280000", "a_counts fast"))

    print("every case behaved" if ok else "at least one case did not behave")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
